---
title: "Week 9.1"
output: html_notebook
---

```{r, include = FALSE}
# the include = FALSE part gets rid of all that junk that gets printed out from loading the libraries

library(dplyr)
library(ggplot2)
library(ggformula)
library(mosaic)
library(supernova)
library(lsr)
library(okcupiddata)
library(dslabs)
library(fivethirtyeight)
library(Lock5Data)
```

# Tiny Fake Home data set

For the purpose of teaching, I'm going to show you a tiny data set. There are two variables: Price and Beds.

```{r}
Beds <- c(1,2,4,5,7)
Price <- Beds * 200

FakeHomes <- data.frame(Price, Beds)

gf_point(Price ~ 1, data = FakeHomes, size = 4)
```
```{r}
Price.stats <- favstats(~ Price, data = FakeHomes)
gf_point(Price ~ 1, data = FakeHomes, size = 4) %>%
  gf_hline(yintercept = ~mean, data = Price.stats, color = "blue") 
```

```{r}
Price.stats <- favstats(~ Price, data = FakeHomes)
gf_point(Price ~ Beds, data = FakeHomes, size = 4) %>%
  gf_hline(yintercept = ~mean, data = Price.stats, color = "blue") %>%
  gf_lm(color = "orange")

```

```{r}
FakeBeds.model <- lm(Price ~ Beds, data = FakeHomes)
```

```{r}
FakeBeds.fun <- makeFun(FakeBeds.model)
FakeBeds.fun(8)
```

```{r}
supernova(FakeBeds.model)
```


```{r}

head(HomesForSale)
```


```{r}
gf_point(Price ~ 1, data = HomesForSale, alpha = .1, size = 3, color = "navyblue")
```


```{r}
Price.stats <- favstats(~ Price, data = HomesForSale)
gf_point(Price ~ Beds, data = HomesForSale, alpha = .1, size = 3, color = "navyblue") %>%
  gf_hline(yintercept = ~mean, data = Price.stats, color = "blue4") %>%
  gf_lm(color = "orange")
```


```{r}
gf_point(Price ~ Baths, data = HomesForSale, alpha = .1, size = 3, color = "darkred") %>%
  gf_lm()

gf_boxplot(Price ~ as.factor(Baths), data = HomesForSale)

lm(Price ~ Baths, data = HomesForSale)

supernova(lm(Price ~ Baths, data = HomesForSale))
```

```{r}
gf_point(Price ~ Size, data = HomesForSale, alpha = .1) %>%
  gf_lm()

lm(Price ~ Size, data = HomesForSale)

supernova(lm(Price ~ Size, data = HomesForSale))
```

```{r}
gf_point(Price ~ State, data = HomesForSale, alpha = .2)
gf_boxplot(Price ~ State, data = HomesForSale, alpha = .2)
```


```{r}
lm(Price ~ State, data = HomesForSale)

supernova(lm(Price ~ State, data = HomesForSale))
```




```{r}
gf_point(Happiness ~ PoorSleepQuality, data = SleepStudy) %>%
  gf_lm()

gf_point(StressScore ~ AverageSleep, data = SleepStudy) %>%
  gf_lm()

lm(Happiness ~ PoorSleepQuality, data = SleepStudy)
supernova(lm(Happiness ~ PoorSleepQuality, data = SleepStudy))

```


